"use client";

import * as React from "react";
import { useParams } from "next/navigation";
import { getSharedQuiz } from "@/lib/share";
import { listAttemptsByToken } from "@/lib/attempts";
import { logShareView } from "@/lib/analytics";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { jsPDF } from "jspdf";

export default function SharedQuizPage() {
  const params = useParams();
  const token = String(params.token);
  const [quiz, setQuiz] = React.useState<any>(null);
  const [password, setPassword] = React.useState("");
  const [error, setError] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [showAnswers, setShowAnswers] = React.useState(false);
  const [leaderboard, setLeaderboard] = React.useState<
    Array<{
      id: string;
      name: string;
      score: number;
      total: number;
      completedAt: number | null;
    }>
  >([]);
  const [leaderboardError, setLeaderboardError] = React.useState<string | null>(null);
  const [accessPassword, setAccessPassword] = React.useState<string | undefined>();

  React.useEffect(() => {
    logShareView(token).catch(() => null);
  }, [token]);

  const fetchQuiz = React.useCallback(
    async (providedPassword?: string) => {
      setLoading(true);
      setError(null);
      try {
        const data = await getSharedQuiz(token, providedPassword);
        setQuiz(data);
        setAccessPassword(providedPassword);
      } catch (err: any) {
        setError("Password required or link invalid.");
      } finally {
        setLoading(false);
      }
    },
    [token]
  );

  React.useEffect(() => {
    fetchQuiz();
  }, [fetchQuiz]);

  React.useEffect(() => {
    if (!quiz) return;
    setLeaderboardError(null);
    listAttemptsByToken(token, accessPassword)
      .then((data) => {
        const sorted = [...data.attempts]
          .filter((attempt) => attempt.status === "completed")
          .sort((a, b) => b.score - a.score)
          .slice(0, 10);
        setLeaderboard(sorted);
      })
      .catch(() => {
        setLeaderboardError("Unable to load leaderboard.");
      });
  }, [quiz, token, accessPassword]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <p className="text-sm text-slate-500">Loading shared quiz...</p>
      </div>
    );
  }

  if (!quiz) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background px-6">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>Protected quiz</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-xs text-slate-500">
              This quiz is password protected. Enter the access code to continue.
            </p>
            <Input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
            />
            {error ? <p className="text-xs text-red-500">{error}</p> : null}
            <Button onClick={() => fetchQuiz(password)} className="w-full">
              Unlock
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const downloadFile = (filename: string, content: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = filename;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = () => {
    const rows = quiz.questions?.flatMap((question: any) =>
      question.options?.map((option: any) => [
        question.prompt,
        option.text,
        option.isCorrect ? "TRUE" : "FALSE"
      ])
    );
    const csv = [["Question", "Option", "Correct"], ...(rows ?? [])]
      .map((row: string[]) =>
        row.map((cell: string) => `"${String(cell).replace(/"/g, '""')}"`).join(",")
      )
      .join("\n");
    downloadFile(`${quiz.title}-shared.csv`, csv, "text/csv");
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    const margin = 14;
    const maxWidth = 180;
    let y = 18;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(String(quiz.title ?? "Shared Quiz"), margin, y);
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text("Generated by QuizMaster AI", margin, y);
    y += 12;

    quiz.questions?.forEach((question: any, index: number) => {
      const prompt = `${index + 1}. ${question.prompt}`;
      const lines = doc.splitTextToSize(prompt, maxWidth);
      if (y + lines.length * 6 > 280) {
        doc.addPage();
        y = 18;
      }
      doc.setFont("helvetica", "bold");
      doc.text(lines, margin, y);
      y += lines.length * 6;

      doc.setFont("helvetica", "normal");
      question.options?.forEach((option: any) => {
        const prefix = showAnswers && option.isCorrect ? "✓ " : "• ";
        const optionText = `${prefix}${option.text}`;
        const optionLines = doc.splitTextToSize(optionText, maxWidth);
        if (y + optionLines.length * 6 > 280) {
          doc.addPage();
          y = 18;
        }
        doc.text(optionLines, margin + 2, y);
        y += optionLines.length * 6;
      });
      y += 4;
    });

    doc.save(`${quiz.title}-shared.pdf`);
  };

  return (
    <div className="min-h-screen bg-background px-6 py-12">
      <div className="mx-auto max-w-3xl space-y-6 print-area">
        <div className="rounded-2xl border border-border bg-white/70 p-6 shadow-soft print-card">
          <p className="text-xs uppercase tracking-widest text-slate-400">
            QuizMaster AI · Shared Quiz
          </p>
          <h1 className="mt-2 text-2xl font-semibold text-foreground">
            {quiz.title}
          </h1>
          <p className="mt-2 text-sm text-slate-500">
            Auto-generated quiz set with curated explanations and flashcards.
          </p>
        </div>
        <div className="flex flex-wrap items-center justify-between gap-3">
          <Button
            onClick={() => {
              window.location.href = `/attempt/${token}`;
            }}
          >
            Attempt quiz
          </Button>
          <Button variant="outline" onClick={handleExportPDF}>
            Export PDF
          </Button>
          <Button variant="outline" onClick={handleExportCSV}>
            Export CSV
          </Button>
          <Button variant="outline" onClick={() => setShowAnswers((prev) => !prev)}>
            {showAnswers ? "Hide answers" : "Show answers"}
          </Button>
        </div>
        <Card>
          <CardHeader>
            <CardTitle>Questions</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {quiz.questions?.map((question: any, index: number) => (
              <div key={question.id ?? index} className="rounded-xl border border-border p-4">
                <p className="text-sm font-medium text-foreground">{question.prompt}</p>
                <ul className="mt-2 space-y-1 text-sm text-slate-600">
                  {question.options?.map((option: any, optionIndex: number) => (
                    <li
                      key={option.id ?? optionIndex}
                      className={
                        showAnswers && option.isCorrect
                          ? "font-semibold text-emerald-600"
                          : ""
                      }
                    >
                      • {option.text}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Flashcards</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-3 md:grid-cols-2">
            {quiz.flashcards?.map((card: any, index: number) => (
              <div key={card.id ?? index} className="rounded-xl border border-border p-4">
                <p className="text-sm font-semibold text-foreground">{card.term}</p>
                <p className="mt-2 text-xs text-slate-500">{card.definition}</p>
              </div>
            ))}
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Leaderboard</CardTitle>
          </CardHeader>
          <CardContent>
            {leaderboardError ? (
              <p className="text-xs text-slate-500">{leaderboardError}</p>
            ) : leaderboard.length === 0 ? (
              <p className="text-xs text-slate-500">
                No completed attempts yet. Be the first to finish!
              </p>
            ) : (
              <div className="space-y-2 text-sm text-slate-600">
                {leaderboard.map((attempt, idx) => (
                  <div
                    key={attempt.id}
                    className="flex items-center justify-between rounded-lg border border-border px-3 py-2"
                  >
                    <span className="font-medium">
                      {idx + 1}. {attempt.name}
                    </span>
                    <span className="font-semibold text-slate-900">
                      {attempt.score}/{attempt.total}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
